export const GAME_CATALOG = [
  {
    type: 'HANGMAN',
    screen: 'Hangman',
    title: 'Hangman',
    subtitle: 'Guess curriculum words before lives run out',
    icon: 'head-question-outline',
    family: 'mci',
    color: '#1B4480',
    tint: '#E3ECF7',
    cover: require('../../assets/games/hangman.png'),
    description: 'Uncover a hidden school term letter by letter before you run out of lives. Stuck? Reveal a subject hint.',
    soloHow: 'Get a random word for your class. Six lives. Optional hint.',
    vsHow: 'Share a room code. Your friend guesses the word. Fewer missed letters wins.',
  },
  {
    type: 'KNOWLEDGE_TOWER',
    screen: 'KnowledgeTower',
    title: 'Knowledge Tower',
    subtitle: 'Stack floors by answering questions',
    icon: 'office-building-outline',
    family: 'mci',
    color: '#7C3AED',
    tint: '#F2F0F7',
    cover: require('../../assets/games/knowledge-tower.png'),
    description: 'Build the tallest tower you can by answering subject questions. Each correct answer adds a floor.',
    soloHow: 'Endless run. Three wrong answers and the tower falls.',
    vsHow: 'Three rounds. Each player gets 45 seconds and up to 5 questions. Highest tower wins.',
  },
  {
    type: 'WORD_SMITH',
    screen: 'WordSmith',
    title: 'Word Smith',
    subtitle: 'Make words from 7 tiles — you pick the clock',
    icon: 'alpha-w-box-outline',
    family: 'mci',
    color: '#15803D',
    tint: '#ECF3EE',
    cover: require('../../assets/games/word-smith.png'),
    description: 'Make as many real words as you can from seven letter tiles before your clock hits zero.',
    soloHow: 'Pick 30s to 2 min. Tap tiles to spell. Longer words score more.',
    vsHow: 'Host picks the round length. Both get the same tiles. Highest score wins.',
  },
  {
    type: 'TIC_TAC_TRIVIA',
    screen: 'TicTacTrivia',
    title: 'Tic Tac Trivia',
    subtitle: 'Claim squares by answering correctly',
    icon: 'grid-outline',
    family: 'ion',
    color: '#C2410C',
    tint: '#FFEDD5',
    cover: require('../../assets/games/tic-tac-trivia.png'),
    description: 'Classic 3×3 — but you only keep a square if you nail the quiz. Miss and it stays open for anyone.',
    soloHow: 'Pick Easy / Medium / Hard and a subject. 12 seconds per question. Beat the rival to three-in-a-row.',
    vsHow: 'Host picks the subject. Take turns. Miss the question and the square stays open.',
  },
  {
    type: 'TARGET_MATH',
    screen: 'TargetMath',
    title: 'Target Math',
    subtitle: 'Hit the target with 5 number tiles',
    icon: 'calculator-outline',
    family: 'ion',
    color: '#A07C10',
    tint: '#F5F0E0',
    cover: require('../../assets/games/target-math.png'),
    description: 'Five number tiles and +, −, ×, ÷. Build in the order you tap and hit the target. You do not have to use every tile.',
    soloHow: 'Pick Easy / Medium / Hard and a clock. Check when the live total matches the bullseye.',
    vsHow: 'Host picks difficulty and time. Same tiles. Hitting the target in fewer steps wins; if tied, faster time wins.',
  },
  {
    type: 'SCRIBBLE',
    screen: 'Scribble',
    title: 'Scribble',
    subtitle: 'Draw a word for a friend to guess',
    icon: 'pencil-outline',
    family: 'ion',
    color: '#0F766E',
    tint: '#CCFBF1',
    cover: require('../../assets/games/scribble.png'),
    description: 'Sketch a school word on the canvas. In a match, your friend watches it replay and has five tries to name it.',
    soloHow: 'Pick a subject, draw the word, then reveal to check yourself.',
    vsHow: 'You draw, your friend guesses. Five tries. Same word pack you can edit.',
  },
];

export function screenForGame(gameType) {
  return GAME_CATALOG.find((g) => g.type === gameType)?.screen || 'GamesHub';
}
